### ISSUE TITLE
This lsfmq github includes object files.  They should be removed

### ISSUE THREAD

**Issue by adamsla** [IBMSpectrumComputing/lsfmq#1]
I noted when browsing the various source, that we are including a compiled version of the message queue stuff in the source repos.  Before committing, you should have done a 'make clean'.  Can you please cleanup these source locations of the object code and binaries?

**Comment by adamsla** [comment]
@PlatformLSF, I assigned you to this one.

**Comment by liuboxa** [comment]
The unexpected object and binary files have been cleaned.

**Comment by adamsla** [comment]
Thanks!
